"""create sales tables

Revision ID: 20595eacd8a1
Revises: fe62a20f527a
Create Date: 2026-09-02 16:49:55.386348
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '20595eacd8a1'
down_revision: Union[str, Sequence[str], None] = 'fe62a20f527a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sale_no', sa.String(length=40), nullable=False),
    sa.Column('status', sa.Enum('completed', 'partially_returned', 'returned', 'reversed', name='salestatus'), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('gross_profit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('sold_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('total_amount >= 0', name=op.f('ck_sales_orders_total_amount_non_negative')),
    sa.CheckConstraint('total_cost >= 0', name=op.f('ck_sales_orders_total_cost_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sales_orders')),
    sa.UniqueConstraint('sale_no', name='uq_sales_orders_sale_no')
    )
    op.create_table('sales_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sales_order_id', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('line_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('line_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('line_profit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('line_amount >= 0', name=op.f('ck_sales_items_line_amount_non_negative')),
    sa.CheckConstraint('line_cost >= 0', name=op.f('ck_sales_items_line_cost_non_negative')),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_sales_items_quantity_positive')),
    sa.CheckConstraint('unit_cost >= 0', name=op.f('ck_sales_items_unit_cost_non_negative')),
    sa.CheckConstraint('unit_price >= 0', name=op.f('ck_sales_items_unit_price_non_negative')),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_orders.id'], name=op.f('fk_sales_items_sales_order_id_sales_orders'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], name=op.f('fk_sales_items_sku_id_skus'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sales_items')),
    sa.UniqueConstraint('sales_order_id', 'sku_id', name='uq_sales_items_order_sku')
    )
    op.create_index(op.f('ix_sales_items_sales_order_id'), 'sales_items', ['sales_order_id'], unique=False)
    op.create_index(op.f('ix_sales_items_sku_id'), 'sales_items', ['sku_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_items_sku_id'), table_name='sales_items')
    op.drop_index(op.f('ix_sales_items_sales_order_id'), table_name='sales_items')
    op.drop_table('sales_items')
    op.drop_table('sales_orders')
    # ### end Alembic commands ###

