"""create skus table

Revision ID: 8aeaa814746e
Revises: 
Create Date: 2026-09-01 18:42:55.990838
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8aeaa814746e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skus',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('local_sku', sa.String(length=32), nullable=False),
    sa.Column('barcode', sa.String(length=64), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('article_number', sa.String(length=100), nullable=False),
    sa.Column('size', sa.String(length=32), nullable=False),
    sa.Column('sale_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'discontinued', name='skustatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('sale_price >= 0', name=op.f('ck_skus_sale_price_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skus')),
    sa.UniqueConstraint('barcode', name='uq_skus_barcode'),
    sa.UniqueConstraint('brand', 'article_number', 'size', name='uq_skus_business_key'),
    sa.UniqueConstraint('local_sku', name=op.f('uq_skus_local_sku'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('skus')
    # ### end Alembic commands ###

