"""create return tables

Revision ID: d9ad6af6ca4e
Revises: 20595eacd8a1
Create Date: 2026-09-02 17:18:44.279996
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd9ad6af6ca4e'
down_revision: Union[str, Sequence[str], None] = '20595eacd8a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('return_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('return_no', sa.String(length=40), nullable=False),
    sa.Column('sales_order_id', sa.Integer(), nullable=False),
    sa.Column('return_type', sa.Enum('customer_return', 'sale_reversal', name='returntype'), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('gross_profit_reversal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('returned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('total_amount >= 0', name=op.f('ck_return_orders_total_amount_non_negative')),
    sa.CheckConstraint('total_cost >= 0', name=op.f('ck_return_orders_total_cost_non_negative')),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_orders.id'], name=op.f('fk_return_orders_sales_order_id_sales_orders'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_return_orders')),
    sa.UniqueConstraint('return_no', name='uq_return_orders_return_no')
    )
    op.create_index(op.f('ix_return_orders_sales_order_id'), 'return_orders', ['sales_order_id'], unique=False)
    op.create_table('return_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('return_order_id', sa.Integer(), nullable=False),
    sa.Column('sales_item_id', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('line_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('line_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('line_profit_reversal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('line_amount >= 0', name=op.f('ck_return_items_line_amount_non_negative')),
    sa.CheckConstraint('line_cost >= 0', name=op.f('ck_return_items_line_cost_non_negative')),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_return_items_quantity_positive')),
    sa.CheckConstraint('unit_cost >= 0', name=op.f('ck_return_items_unit_cost_non_negative')),
    sa.CheckConstraint('unit_price >= 0', name=op.f('ck_return_items_unit_price_non_negative')),
    sa.ForeignKeyConstraint(['return_order_id'], ['return_orders.id'], name=op.f('fk_return_items_return_order_id_return_orders'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sales_item_id'], ['sales_items.id'], name=op.f('fk_return_items_sales_item_id_sales_items'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], name=op.f('fk_return_items_sku_id_skus'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_return_items')),
    sa.UniqueConstraint('return_order_id', 'sales_item_id', name='uq_return_items_order_sales_item')
    )
    op.create_index(op.f('ix_return_items_return_order_id'), 'return_items', ['return_order_id'], unique=False)
    op.create_index(op.f('ix_return_items_sales_item_id'), 'return_items', ['sales_item_id'], unique=False)
    op.create_index(op.f('ix_return_items_sku_id'), 'return_items', ['sku_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_return_items_sku_id'), table_name='return_items')
    op.drop_index(op.f('ix_return_items_sales_item_id'), table_name='return_items')
    op.drop_index(op.f('ix_return_items_return_order_id'), table_name='return_items')
    op.drop_table('return_items')
    op.drop_index(op.f('ix_return_orders_sales_order_id'), table_name='return_orders')
    op.drop_table('return_orders')
    # ### end Alembic commands ###

