"""remove sale price from skus

Revision ID: db4770b27713
Revises: fc69448b4fb5
Create Date: 2026-09-05 16:46:24.954423
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = 'db4770b27713'
down_revision: Union[str, Sequence[str], None] = 'fc69448b4fb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_skus_sale_price_non_negative'), 'skus', type_='check')
    op.drop_column('skus', 'sale_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    op.add_column(
        "skus",
        sa.Column(
            "sale_price",
            mysql.DECIMAL(precision=12, scale=2),
            server_default=sa.text("0.00"),
            nullable=False,
        ),
    )

    op.alter_column(
        "skus",
        "sale_price",
        existing_type=mysql.DECIMAL(
            precision=12,
            scale=2,
        ),
        server_default=None,
        existing_nullable=False,
    )

    op.create_check_constraint(
        op.f("ck_skus_sale_price_non_negative"),
        "skus",
        "sale_price >= 0",
    )

