"""create inventory corrections table

Revision ID: fc69448b4fb5
Revises: d9ad6af6ca4e
Create Date: 2026-09-02 17:54:37.429497
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fc69448b4fb5'
down_revision: Union[str, Sequence[str], None] = 'd9ad6af6ca4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_corrections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('correction_no', sa.String(length=40), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('quantity_change', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('inventory_value_change', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('before_qty', sa.Integer(), nullable=False),
    sa.Column('after_qty', sa.Integer(), nullable=False),
    sa.Column('before_avg_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('after_avg_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reason', sa.Enum('duplicate_scan', 'missed_scan', 'wrong_sku', 'damage', 'other', name='correctionreason'), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('after_avg_cost >= 0', name=op.f('ck_inventory_corrections_after_avg_cost_non_negative')),
    sa.CheckConstraint('after_qty >= 0', name=op.f('ck_inventory_corrections_after_qty_non_negative')),
    sa.CheckConstraint('before_avg_cost >= 0', name=op.f('ck_inventory_corrections_before_avg_cost_non_negative')),
    sa.CheckConstraint('before_qty >= 0', name=op.f('ck_inventory_corrections_before_qty_non_negative')),
    sa.CheckConstraint('quantity_change <> 0', name=op.f('ck_inventory_corrections_quantity_change_not_zero')),
    sa.CheckConstraint('unit_cost >= 0', name=op.f('ck_inventory_corrections_unit_cost_non_negative')),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], name=op.f('fk_inventory_corrections_sku_id_skus'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_corrections')),
    sa.UniqueConstraint('correction_no', name='uq_inventory_corrections_correction_no')
    )
    op.create_index(op.f('ix_inventory_corrections_sku_id'), 'inventory_corrections', ['sku_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_corrections_sku_id'), table_name='inventory_corrections')
    op.drop_table('inventory_corrections')
    # ### end Alembic commands ###

