"""create inventory tables

Revision ID: fe62a20f527a
Revises: 8aeaa814746e
Create Date: 2026-09-01 19:17:03.984696
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fe62a20f527a'
down_revision: Union[str, Sequence[str], None] = '8aeaa814746e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('on_hand_qty', sa.Integer(), nullable=False),
    sa.Column('reserved_qty', sa.Integer(), nullable=False),
    sa.Column('avg_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('avg_cost >= 0', name=op.f('ck_inventories_avg_cost_non_negative')),
    sa.CheckConstraint('on_hand_qty >= 0', name=op.f('ck_inventories_on_hand_qty_non_negative')),
    sa.CheckConstraint('reserved_qty <= on_hand_qty', name=op.f('ck_inventories_reserved_qty_not_exceed_on_hand')),
    sa.CheckConstraint('reserved_qty >= 0', name=op.f('ck_inventories_reserved_qty_non_negative')),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], name=op.f('fk_inventories_sku_id_skus'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventories')),
    sa.UniqueConstraint('sku_id', name='uq_inventories_sku_id')
    )
    op.create_table('stock_movements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('movement_no', sa.String(length=40), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('movement_type', sa.Enum('inbound', 'sale', 'return', 'adjustment', 'reversal', name='stockmovementtype'), nullable=False),
    sa.Column('quantity_change', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('before_qty', sa.Integer(), nullable=False),
    sa.Column('after_qty', sa.Integer(), nullable=False),
    sa.Column('before_avg_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('after_avg_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reference_no', sa.String(length=100), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('after_avg_cost >= 0', name=op.f('ck_stock_movements_after_avg_cost_non_negative')),
    sa.CheckConstraint('after_qty >= 0', name=op.f('ck_stock_movements_after_qty_non_negative')),
    sa.CheckConstraint('before_avg_cost >= 0', name=op.f('ck_stock_movements_before_avg_cost_non_negative')),
    sa.CheckConstraint('before_qty >= 0', name=op.f('ck_stock_movements_before_qty_non_negative')),
    sa.CheckConstraint('unit_cost >= 0', name=op.f('ck_stock_movements_unit_cost_non_negative')),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], name=op.f('fk_stock_movements_sku_id_skus'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_movements')),
    sa.UniqueConstraint('movement_no', name=op.f('uq_stock_movements_movement_no'))
    )
    op.create_index(op.f('ix_stock_movements_sku_id'), 'stock_movements', ['sku_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_movements_sku_id'), table_name='stock_movements')
    op.drop_table('stock_movements')
    op.drop_table('inventories')
    # ### end Alembic commands ###

